# -*- coding: utf-8 -*-
"""GUI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeQzj_lD7zKdrhCIOH6TT_taAh7lMKMU
"""

from tkinter import *
import tkinter.messagebox

class ATM:
    def __init__(self, master):
        self.master = master
        master.title("ATM Page")

        # create label for heading
        self.heading_label = Label(master, text="Welcome to BHUGAN Bank ATM", font=("Helvetica", 20))
        self.heading_label.pack(pady=20)

        # create label for amount
        self.amount_label = Label(master, text="Enter the amount:", font=("Helvetica", 16))
        self.amount_label.pack(pady=10)

        # create entry box for amount
        self.amount_entry = Entry(master, font=("Helvetica", 16))
        self.amount_entry.pack(pady=10)

        # create button to withdraw money
        self.withdraw_button = Button(master, text="Withdraw", font=("Helvetica", 16), command=self.withdraw_money)
        self.withdraw_button.pack(pady=20)

    def withdraw_money(self):
        amount = self.amount_entry.get()
        # check if the amount is valid and can be withdrawn
        if amount == "":
            tkinter.messagebox.showerror("Error", "Please enter the amount!")
        elif not amount.isdigit():
            tkinter.messagebox.showerror("Error", "Invalid amount! Please enter digits only.")
        elif int(amount) > 5000:
            tkinter.messagebox.showerror("Error", "Sorry, you cannot withdraw more than 5000.")
        else:
            tkinter.messagebox.showinfo("Success", f"{amount} withdrawn successfully.")
            self.amount_entry.delete(0, END)


root = Tk()
my_gui = ATM(root)
root.mainloop()